services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: spa_app
    image: spa_app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://app:!ChangeMe!@db:5432/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    container_name: spa_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:rw
    restart: always

volumes:
  data: