services:
  app:
    container_name: spa_app_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://app:ChangeMe@db:5432/app
    command: npm run dev